name: Deploy GitHub Pages
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Firebase config
        run: |
          echo "window.FIREBASE_CONFIG = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
          };" > public/firebase-config.js

      - name: Build project (if needed)
        run: |
          if [ -f package.json ]; then npm ci && npm run build; fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
